### ISSUE TITLE
Adding the App to the Web Interface!

### ISSUE THREAD

**Issue by sallyhaj** [flathub/org.getzola.zola#7]
Hello there,
I have tried searching 'zola' on the web interface, but it shows nothing.
I headed to #flathub group on Matrix, they said, they reason behind that is that: it need to get appears there two things:
1- Icon.
2- Screenshot.

Could you please update that, so it can show there!

Thank you so much.

**Comment by Newbytee** [comment]
Hi, sorry, but this is deliberate. Flathub does not list command line apps in the web interface. Maybe we should add a readme explaining what this is. Why do you want it in the web interface?

**Comment by sallyhaj** [comment]
Oh, I didn't know that.
Nothing very important, but thought of that, some people use the web to search about available application, so, existing/adding such apps, might help to spread the usability of them.
Thank you.
